spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paslas_db
    username: admin
    password: admin123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    link: http://localhost:8080/api/user/email/verify
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  profiles:
    active: dev

application:
  security:
    jwt:
      secret-key: dGhpc19pc19hX3Zlcnlfc2VjdXJlX2tleV9mb3Jfand0IQ==
      expiration: 604800000 # 7 day
    cookie:
      expiration: 604800 # 7 day
    join-code:
      charset: "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"
      length: 6
  cors:
    allowed-origins:
      - http://localhost:3000